name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc g++

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Configure CMake
      run: mkdir -p build && cd build && cmake ..

    - name: Build the project
      run: cd build && make
