name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc g++

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Install GoogleTest
      run: sudo apt-get install -y libgtest-dev

    - name: Configure CMake
      run: cd test/ && mkdir build && cd build && cmake ..

    - name: Build and Run Tests
      run: cd test/build && make && ./run-tests
