name: Validate Commit Messages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, edited, reopened]

jobs:
  commit-check:
    name: Check commit messages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get commit messages
      run: |
        chmod +x scripts/check-commit-messages.sh
        ./scripts/check-commit-messages.sh
